watchdog:
  mechmarket:
    interval: 5
    users:
      - sendto: H3NT4I
        special:
          - Eat_the_food
      - sendto: timidsa
        ignore:
          - ezeallinh
          - scud80
          - legit309
          - LightningXI
          - expensive-hobbies
          - ggZyg
          - crusader_alex
        special: 
          - Eat_the_food
          - TimidSA
          - mgsickler
        listingtypes:
          - GB
          - IC
          - Vendor
        search:
          - term: solarized dark
          - term: Novatouch
            exclude:
              - novatouch slider
              - novatouch stem
          - term: Panda
            exclude:
              - trash panda
              - panda stem
              - gaf panda
              - stash panda
              - hash panda
              - unholy panda
              - cashed panda
              - putrid panda
          - term: Dolch Pac
            exclude:
              - dolch pac keys
              - dolch pac key set
              - dolch pac keyset
              - dolch pac keycap
              - dolch pac key cap
              - dolch pac cap
              - dolch pac set
  geekhack:
    users:
      - username: bisoromi
        id: <@177965123288170496>
        topics:
          - jane;yuktsi
          - kyuu;quantastrophus
          - h87a;hineybush
      - username: H3NT4I
        id: <@296815003153989644>
        topics:
          - jane;yuktsi
          - kyuu;quantastrophus
          - h87a;hineybush
      - username: r3msky
        id: <@307980991178342410>
        topics:
          - jane;yuktsi
      - username: tr4656
        id: <@90276021617590272>
        topics:
          - jane;yuktsi
    updatedTopics:
      "95054":
        topicName: TGR Alice
        topicAuthor: yuktsi
        subscribers:
          tr4656: <@90276021617590272>
          bisoromi: <@177965123288170496>
          r3msky: <@307980991178342410>
          h3nt4i: <@296815003153989644>