watchdog:
  mechmarket:
    interval: 5
    users:
      - sendto: timidsa
        ignore:
          - ezeallinh
        special: 
          - Eat_the_food
          - TimidSA
          - mgsickler
        listingtypes:
          - GB
          - IC
          - Vendor
        search:
          - term: Novatouch
            exclude:
              - novatouch slider
              - novatouch stem
          - term: Panda
            exclude:
              - trash panda
              - panda stem
              - gaf panda
              - stash panda
              - hash panda
          - term: Dolch Pac
            exclude:
              - dolch pac keys
              - dolch pac key set
              - dolch pac keyset
              - dolch pac keycap
              - dolch pac key cap
              - dolch pac cap
              - dolch pac set